version: '2'
services:
  ccrimongo:
    container_name: ccrimongo
    image: mongo:3.6.3
    ports:
    - 27107:27107

  ccridocument:
    container_name: ccridocument
    image: thorlogic/ccri-document:latest
    depends_on:
    - ccrimongo
    links:
    - ccrimongo
    environment:
    - fhir.resource.serverBase=http://127.0.0.1:8181/a2si-appointment-poc/STU3
    - fhir.resource.serverName=Appointment Booking POC FHIR Server
    - fhir.resource.serverVersion=3.5.1-SNAPSHOT
    - spring.data.mongodb.uri=mongodb://ccrimongo:27017/appointment
    - spring.data.mongodb.database=appointment
    ports:
    - 8181:8181
    extra_hosts:
    # Define an alias to loop back for REST Connections
    - "$${FHIR_SERVER_BASE_HOST}:127.0.0.1"
